
language: php

matrix:
  include:
    - php: 7
      env: TYPO3_VERSION=^8.7
    - php: 7.1
      env: TYPO3_VERSION=^8.7
    - php: 7
      env: TYPO3_VERSION=dev-master
    - php: 7.1
      env: TYPO3_VERSION=dev-master
  allow_failures:
    - env: TYPO3_VERSION=dev-master

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer --version
